"""02 add blacklist entities

Revision ID: c6b064c65fd4
Revises: 18fca3714efd
Create Date: 2023-04-29 10:52:28.520473

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "c6b064c65fd4"
down_revision = "18fca3714efd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "db_blacklisted_client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "host",
            sqlalchemy_utils.types.ip_address.IPAddressType(length=50),
            nullable=True,
        ),
        sa.Column("until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_db_blacklisted_client_until"),
        "db_blacklisted_client",
        ["until"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_db_blacklisted_client_until"),
        table_name="db_blacklisted_client",
    )
    op.drop_table("db_blacklisted_client")
    # ### end Alembic commands ###
