"""01-inital-db

Revision ID: ec11dea427d3
Revises: 
Create Date: 2023-04-25 12:25:30.712097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec11dea427d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_shortened_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('original', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original'),
    sa.UniqueConstraint('value')
    )
    op.create_index(op.f('ix_db_shortened_url_created_at'), 'db_shortened_url', ['created_at'], unique=False)
    op.create_table('db_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1000), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_db_user_created_at'), 'db_user', ['created_at'], unique=False)
    op.create_table('db_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('user_agent', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_shortened_url_use',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['db_client.id'], ),
    sa.ForeignKeyConstraint(['url_id'], ['db_shortened_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_shortened_url_use_created_at'), 'db_shortened_url_use', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_shortened_url_use_created_at'), table_name='db_shortened_url_use')
    op.drop_table('db_shortened_url_use')
    op.drop_table('db_client')
    op.drop_index(op.f('ix_db_user_created_at'), table_name='db_user')
    op.drop_table('db_user')
    op.drop_index(op.f('ix_db_shortened_url_created_at'), table_name='db_shortened_url')
    op.drop_table('db_shortened_url')
    # ### end Alembic commands ###
